#!/usr/bin/env bash
# fetch-research-swarm.sh
#
# CI helper: download the `research-agent` single-file PyInstaller
# binary matching the current runner's platform/arch, drop it at
# `apps/os/build-resources/research-swarm/research-agent`, and
# `chmod +x` it so electron-builder picks it up via `extraResources`.
#
# Mirrors scripts/fetch-swf-node.sh — same pattern, different repo.
#
# Naming convention (set upstream in dmarzzz/research-swarm by the
# PyInstaller release pipeline):
#
#   research-agent-<version>-mac-arm64
#   research-agent-<version>-mac-x64
#   research-agent-<version>-linux-x64
#   research-agent-<version>-linux-arm64
#
# Released at:
#   https://github.com/dmarzzz/research-swarm/releases/download/v<version>/research-agent-<version>-<platform>-<arch>
#
# Version selection:
#   - Honors `RESEARCH_SWARM_VERSION` env var (without the leading "v") if set.
#   - Otherwise resolves the latest release tag via the GitHub API.
#
# Falls back to a stub on:
#   - Windows (any arch). research-swarm hasn't published Windows
#     PyInstaller assets yet — see the workflow's `notes` section.
#     The Electron supervisor (apps/os/swarm-node.js) sees the stub
#     binary and surfaces "swarm not installed" in the panel.
#   - Targets where upstream has no matching asset yet — leaves a stub
#     binary in place so electron-builder still has something to pack
#     and the spawn logic can be exercised end-to-end. Stub prints a
#     warning + exits non-zero so swarm-node.js's spawn-failure path
#     fires cleanly (research-agent is invoke-and-exit, not a daemon,
#     so we shouldn't sleep-forever here like the swf-node stub does).
#
# Idempotent: re-running with the same version is a no-op if the
# binary already exists. Pass `--force` to redownload.

set -euo pipefail

REPO="dmarzzz/research-swarm"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEST_DIR="$REPO_ROOT/apps/os/build-resources/research-swarm"
DEST_BIN="$DEST_DIR/research-agent"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help)
      sed -n '2,40p' "$0"
      exit 0
      ;;
  esac
done

# ── platform / arch detection ───────────────────────────────────────
case "$(uname -s)" in
  Darwin)  PLATFORM="mac" ;;
  Linux)   PLATFORM="linux" ;;
  MINGW*|MSYS*|CYGWIN*)
    PLATFORM="windows"
    ;;
  *)
    echo "[fetch-research-swarm] unknown uname -s='$(uname -s)' — skipping"
    exit 0
    ;;
esac

case "$(uname -m)" in
  arm64|aarch64) ARCH="arm64" ;;
  x86_64|amd64)  ARCH="x64"   ;;
  *)
    echo "[fetch-research-swarm] unsupported arch '$(uname -m)' — skipping"
    exit 0
    ;;
esac

# Allow CI to override target via env vars (mirrors fetch-swf-node.sh).
PLATFORM="${RESEARCH_SWARM_PLATFORM:-$PLATFORM}"
ARCH="${RESEARCH_SWARM_ARCH:-$ARCH}"

mkdir -p "$DEST_DIR"

install_stub() {
  echo "[fetch-research-swarm] installing stub at $DEST_BIN"
  cat > "$DEST_BIN" <<'STUB'
#!/usr/bin/env bash
# research-agent stub — generated by scripts/fetch-research-swarm.sh
# when no upstream release was available at bundle time (or when this
# platform isn't supported by the upstream PyInstaller workflow yet —
# Windows today). The Electron swarm panel will show a graceful
# "swarm not installed" error rather than crashing.
echo "[research-agent:stub] WARNING: this is a placeholder binary, not the real research-agent." >&2
echo "[research-agent:stub] No upstream release available at bundle time for this platform/arch." >&2
echo "[research-agent:stub] Args: $*" >&2
exit 127
STUB
  chmod +x "$DEST_BIN"
}

# research-swarm hasn't built Windows PyInstaller assets yet. Skip the
# download attempt entirely on Windows and ship a stub so the installer
# still packages successfully. swarm-node.js's resolveAgentBinary()
# will surface this as "swarm not installed" in the panel.
if [ "$PLATFORM" = "windows" ]; then
  echo "[fetch-research-swarm] research-swarm has no Windows PyInstaller asset yet — installing stub"
  install_stub
  exit 0
fi

# ── version resolution ─────────────────────────────────────────────
VERSION="${RESEARCH_SWARM_VERSION:-}"
if [ -z "$VERSION" ]; then
  echo "[fetch-research-swarm] resolving latest release of $REPO ..."
  if [ -n "${GITHUB_TOKEN:-}" ]; then
    LATEST_JSON="$(curl -fsSL \
      -H "Authorization: Bearer $GITHUB_TOKEN" \
      -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/$REPO/releases/latest" 2>/dev/null || true)"
  else
    LATEST_JSON="$(curl -fsSL \
      -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/$REPO/releases/latest" 2>/dev/null || true)"
  fi
  if [ -z "$LATEST_JSON" ] || echo "$LATEST_JSON" | grep -q '"message":'; then
    echo "[fetch-research-swarm] no latest release available yet — installing stub"
    VERSION=""
  else
    VERSION="$(printf '%s' "$LATEST_JSON" \
      | tr ',' '\n' \
      | grep -E '"tag_name"' \
      | head -1 \
      | sed -E 's/.*"tag_name"[[:space:]]*:[[:space:]]*"v?([^"]+)".*/\1/')"
    if [ -z "$VERSION" ]; then
      echo "[fetch-research-swarm] couldn't parse tag_name from API response — installing stub"
    fi
  fi
fi

if [ -z "$VERSION" ]; then
  install_stub
  exit 0
fi

ASSET="research-agent-${VERSION}-${PLATFORM}-${ARCH}"
URL="https://github.com/$REPO/releases/download/v${VERSION}/${ASSET}"

if [ "$FORCE" -ne 1 ] && [ -f "$DEST_BIN" ] && [ -f "$DEST_DIR/.version" ] && [ "$(cat "$DEST_DIR/.version" 2>/dev/null)" = "$VERSION-$PLATFORM-$ARCH" ]; then
  echo "[fetch-research-swarm] $ASSET already cached at $DEST_BIN — skipping"
  exit 0
fi

echo "[fetch-research-swarm] downloading $ASSET"
echo "[fetch-research-swarm]   from $URL"

TMP="$(mktemp -t research-agent-fetch.XXXXXX)"
trap 'rm -f "$TMP"' EXIT
HTTP_STATUS="$(curl -fSL -w '%{http_code}' -o "$TMP" "$URL" 2>/dev/null || echo "000")"

if [ ! -s "$TMP" ] || [ "${HTTP_STATUS:-000}" = "000" ] || [ "$(printf '%s' "$HTTP_STATUS" | tail -c 3)" = "404" ]; then
  echo "[fetch-research-swarm] download failed (HTTP $HTTP_STATUS) — no asset for $PLATFORM-$ARCH at v$VERSION yet"
  echo "[fetch-research-swarm] falling back to stub so the build pipeline still succeeds"
  install_stub
  exit 0
fi

mv "$TMP" "$DEST_BIN"
trap - EXIT
chmod +x "$DEST_BIN"
printf '%s-%s-%s' "$VERSION" "$PLATFORM" "$ARCH" > "$DEST_DIR/.version"
echo "[fetch-research-swarm] installed research-agent v$VERSION ($PLATFORM-$ARCH) at $DEST_BIN"
