// Curated Intel preview for the Constellation surface.
// These signals are coordinator moves: compact reads that point to a catalytic
// action, a falsification path, and the evidence surfaces to inspect.
export const INTEL_SIGNALS = [
  {
    id: "move-smithers-workflow-wedge",
    tier: "inferred",
    kind: "catalytic-pairing",
    title: "Smithers wins by becoming one team's workflow nerve, not another agent platform",
    entities: [
      "person:will-cory",
      "project:searxng-wth-frnds",
      "project:tinycloud",
    ],
    displayEntities: [
      "Will Cory / Smithers",
      "Dmarz / searxng-wth-frnds",
      "TinyCloud",
      "Andrew-style internal workflow pain",
    ],
    claim: "The Smithers opportunity is not that agentic engineering is hot. The sharper read is that Will is already surrounded by teams whose work is becoming too complex for one-shot agents, but Smithers only becomes legible when one live team lets it own a repeatable workflow end to end.",
    shapeRotation: "Rotate Smithers from horizontal orchestration language into one boring, paid-for, repeatable operating loop: a workflow that survives retries, review, handoff, and human approval for a specific team.",
    chain: [
      "Smithers office hours repeatedly circles differentiation, crowded frontier tooling, and whether the target is everyone or a specific workflow buyer",
      "the same transcript names internal overlap with TinyCloud, Andrew/Teleport-like workflow, Flashbots-style internal needs, and other cohort teams",
      "searxng-wth-frnds/research-swarm is a concrete local search/research substrate rather than another abstract agent platform",
      "therefore: the cohort itself is the customer-discovery instrument; the missing move is a focused workflow wedge, not more generic product ideation",
    ],
    coordinatorMove: "Put Will, Dmarz, and one workflow-pained team in a 30-minute session. Ban platform language. Force one question: 'what exact recurring internal workflow would you pay to make boring by Friday?'",
    introduction: "Stage Will with Dmarz around searxng-wth-frnds/research-swarm, then add the team with the most painful recurring agent handoff. The point is to extract a workflow, not to demo Smithers.",
    watchFor: "If the answer stays 'agentic engineering for everyone,' the edge is dissolving into frontier-tool normalization. If one painful workflow repeats across two teams, Smithers has a wedge.",
    limits: "This is an inferred product-read from office-hours and public/project material. It should be treated as a coordinator hypothesis until the wedge session produces a named workflow and a willingness-to-pay signal.",
    sourceReceipts: [
      "Smithers office-hours synthesis",
      "Will Cory profile and project material",
      "searxng-wth-frnds project metadata",
      "TinyCloud project metadata",
    ],
  },
  {
    id: "move-james-teaches-infra-turn",
    tier: "inferred",
    kind: "hidden-teacher",
    title: "James is the worked example for teams stuck before the infra-to-product turn",
    entities: [
      "person:james-barnes",
      "project:etherea",
      "project:elizaos",
      "project:jjhub",
    ],
    displayEntities: [
      "James Barnes",
      "Etherea",
      "elizaOS / Shaw",
      "JJHub / Will Cory",
    ],
    claim: "Several builders are preserving too many infrastructure futures at once. James appears to have already made the hard turn: park the infra darling, commit to one concrete downstream surface, and let that surface discipline the architecture.",
    shapeRotation: "Rotate James from another impressive builder into a living curriculum: a peer who can show what had to be killed before a single downstream product could become real.",
    chain: [
      "the dossier signal pattern identifies phase-shapes: one builder has already crossed the exact turn another builder is stuck before",
      "Etherea/James is legible as an egress-attestation-to-creative-AI turn rather than another broad infra thesis",
      "Will/Shaw-style cases are vulnerable to staying diffuse across infrastructure, community dependence, and several possible surfaces",
      "therefore: James should not be presented as a profile; he should be used as a peer teacher for the specific turn from infrastructure optionality to product commitment",
    ],
    coordinatorMove: "Ask James to run a small 'what I killed to ship one surface' conversation with Will/Shaw-style builders. The point is not advice; it is lived proof that the turn is survivable.",
    introduction: "Make it a 3-person room, not a panel: James plus one diffuse infra builder plus one coordinator who only asks about decisions killed, surfaces chosen, and what changed after commitment.",
    watchFor: "The read fails if James has not actually narrowed execution, or if the other builders' blocker is demand rather than inability to kill optionality.",
    limits: "This is a phase-shape read. It should not become a verdict on any builder; it is useful only if the receiving team recognizes the stuck-before pattern in themselves.",
    sourceReceipts: [
      "James Barnes profile and project material",
      "Etherea project material",
      "elizaOS project context",
      "JJHub / Smithers project context",
    ],
  },
  {
    id: "move-tee-trust-root-room",
    tier: "inferred",
    kind: "cross-domain",
    title: "The privacy teams are each selling a different answer to the same trust-root question",
    entities: [
      "project:trustless-tee",
      "project:bitrouter",
      "project:dealproof",
      "project:teesql",
    ],
    displayEntities: [
      "Trustless TEE / Quintus",
      "Bitrouter",
      "DealProof",
      "TeeSQL",
      "TEE-adjacent cohort teams",
    ],
    claim: "TeeSQL, SignalStack, Conclave, DealProof, Bitrouter, and Trustless TEE are not merely adjacent because they mention TEEs. They are each asking a user to relocate trust from a person, company, venue, or contract into a machine-verifiable boundary. The unowned cohort question is: which trust root is each product actually selling?",
    shapeRotation: "Rotate the TEE cluster from parallel technical pitches into a shared trust map. Once each team names the party, failure mode, and proof promise, the cohort can see which teams are complements, critiques, or accidental duplicates.",
    chain: [
      "repo intelligence exposes inspectable TEE/attestation surfaces for some teams",
      "candidate/project material repeatedly touches routing, attestation, confidential compute, or proof surfaces",
      "Trustless TEE's public identity points at open/verifiable silicon rather than vendor-root trust",
      "therefore: the highest-value session is not a pitch round; it is a trust-root mapping room where each team states exactly what it asks users to trust",
    ],
    coordinatorMove: "Run a 45-minute trust-root map with Trustless TEE, Bitrouter, DealProof, TeeSQL, and one skeptical coordinator. Output one table: trusted party, failure mode, user-visible promise, possible mitigation.",
    introduction: "Put Trustless TEE in the mirror role, not the competitor role. Add TeeSQL for attested storage, SignalStack for private inference in an existing messenger, and Conclave for confidential negotiation.",
    watchFor: "If teams cannot name their trust root in one sentence, the cohort has a shared blind spot. If they can, Trustless TEE becomes either a bridge, a critique, or an unnecessary parallel track.",
    limits: "This read deliberately compresses several projects into one lens. It must be validated by each team naming its own trust boundary; the panel should not pretend the map already exists.",
    sourceReceipts: [
      "Trustless TEE project material",
      "Bitrouter project material",
      "DealProof project material",
      "TeeSQL project material",
      "SignalStack project material",
      "Conclave project material",
      "TEE / attestation public repo signal",
    ],
  },
  {
    id: "move-conclave-demand-test",
    tier: "inferred",
    kind: "phase-shape",
    title: "Conclave risks repeating the shipped-then-closed loop unless Prakhar front-loads demand",
    entities: [
      "project:conclave",
      "person:prakhar",
    ],
    displayEntities: [
      "Conclave",
      "Prakhar Ojha",
      "Smart Bet precedent",
      "demand-test loop",
    ],
    claim: "The danger is not whether Prakhar can build. The danger is that building is the comfortable move. The higher-leverage question is whether Conclave can force demand contact early enough to avoid repeating the completed loop: build, ship, run, close when the user base does not form.",
    shapeRotation: "Rotate Prakhar's prior shutdown from a negative mark into an instrument: the old failure should become the earliest-warning test for the new product.",
    chain: [
      "repo intelligence shows Prakhar/Conclave has enough substrate to inspect as real work rather than pure story",
      "the dossier signal pattern treats prior shipped-then-closed loops as teachable precedents, not stigma",
      "Conclave-like ambition can diffuse across retrieval, agents, routing, and marketplace surfaces",
      "therefore: the coordinator move is to make Prakhar's prior loop the explicit curriculum for Conclave's next two weeks",
    ],
    coordinatorMove: "Ask Prakhar for the earliest signal that would have saved Smart Bet, then require Conclave to collect that signal before adding another major surface.",
    introduction: "Pair Prakhar with one person who will not be impressed by more features, only by live demand proof. The useful room is customer-discovery pressure, not architecture review.",
    watchFor: "If Prakhar can name the failed early signal and design a test this week, the old loop becomes an asset. If not, Conclave may be re-entering the same build-first groove.",
    limits: "This is a validation hypothesis about loop shape, not about code quality. The repo can be real and the market test can still be missing; both facts can be true at once.",
    sourceReceipts: [
      "Conclave project material",
      "Prakhar Ojha profile material",
      "Conclave public repo signal",
      "Smart Bet public precedent signal",
    ],
  },
  {
    id: "move-daedalus-pilot-surface",
    tier: "inferred",
    kind: "tension-map",
    title: "Daedalus has two possible buyers hiding under one prediction-market story",
    entities: [
      "project:daedalus",
      "person:freya-zhang",
      "person:leo-fang",
    ],
    displayEntities: [
      "Daedalus",
      "Freya Zhang",
      "Leo Fang",
      "prediction-market venues",
      "portfolio-risk distribution partners",
    ],
    claim: "Daedalus can sound like one project while actually containing two very different sales motions: institution-facing microstructure infrastructure for venues and market makers, or a packaged hedging feature for portfolio holders through a broker-like partner. The coordinator value is to force that fork early, because each path needs different proof, different introductions, and different language.",
    shapeRotation: "Rotate the question from 'is the prediction-market model sophisticated?' to 'which buyer gets a painful improvement first?' The math is not the bottleneck if the pilot surface is ambiguous.",
    chain: [
      "project material frames Daedalus as market-native infrastructure for prediction-market liquidity, protected execution, and institutional participants",
      "office hours also surfaces a compelling consumer/partner frame: analyze portfolio exposure, explain upstream risks, and package prediction-market hedges through an IBKR-like distribution path",
      "those two frames require different pilots: venue/order-flow integration versus education, compliance, and partner distribution",
      "therefore: Daedalus needs a buyer-surface decision before more architecture debate; otherwise the same research can be pulled toward incompatible GTM tests",
    ],
    coordinatorMove: "Run a forked-pilot decision with Daedalus: one column for venue/maker infrastructure, one for broker-style portfolio hedging. Require one named pilot user, one proof metric, and one intro request for each, then pick the faster live test.",
    introduction: "Introduce them either to prediction-market venue or maker operators if they choose protected execution, or to a broker/portfolio-product person if they choose packaged hedging. Do not mix those asks in the same intro.",
    watchFor: "If the team cannot choose a first pilot surface, the product may keep escaping into elegant market-structure language. If one buyer names the pain in their own words, the research has a deployment path.",
    limits: "This is a strategic fork read from application material and office-hours discussion. It should not collapse Daedalus into retail; the point is to prevent two valid GTM paths from blurring.",
    sourceReceipts: [
      "Daedalus project material",
      "Daedalus office-hours synthesis",
      "Freya Zhang profile material",
      "Leo Fang profile material",
    ],
  },
  {
    id: "move-hudson-signalstack-translator",
    tier: "inferred",
    kind: "hidden-teacher",
    title: "Hudson may be SignalStack's missing product translator, not just its second engineer",
    entities: [
      "person:hudson",
      "project:signalstack",
      "person:ron-turetzky",
    ],
    displayEntities: [
      "Hudson Headley",
      "Ron Turetzky",
      "SignalStack",
      "privacy-first AI users",
    ],
    claim: "SignalStack's technical promise is strong but easy to trap inside attestation language. Hudson's interview material shows a rarer capability: translating across engineering, philosophy, organizational design, and everyday human use. That may be the exact missing bridge between Ron's technical privacy proof and a product people can feel in Signal.",
    shapeRotation: "Rotate Hudson from support engineer into product translator: the person who turns TEE guarantees into private daily rituals, user stories, and simple language without weakening the technical truth.",
    chain: [
      "SignalStack sells private AI where the user already is: inside Signal, with TEE-backed processing and verification",
      "Hudson's material repeatedly points at translation across domains, identity, organization, and the gap between abstract systems and lived use",
      "the cohort already contains privacy-heavy teams whose strongest claims can become illegible when expressed only as cryptographic infrastructure",
      "therefore: Hudson is not merely execution capacity; he should be used to convert SignalStack's trust proof into the human use cases that make the proof matter",
    ],
    coordinatorMove: "Ask Hudson to write three SignalStack user scenes in plain language before another technical demo: one journalist/source, one lawyer/client, one developer/security researcher. Ron verifies the technical promises after the scenes are emotionally legible.",
    introduction: "Put Hudson and Ron with one non-TEE person who has a real private communication need. Make Hudson explain the product first; Ron only enters to verify what is technically enforceable.",
    watchFor: "If Hudson can make a non-TEE user say 'I know when I would use this,' SignalStack has a product bridge. If the explanation returns to attestation mechanics, the product is still over-speaking to insiders.",
    limits: "This is a person-role hypothesis grounded in interview and project material. It should be offered as a way to use Hudson's strengths, not as a fixed identity label.",
    sourceReceipts: [
      "Hudson profile and interview synthesis",
      "SignalStack project material",
      "Ron Turetzky / SignalStack public project signal",
    ],
  },
];
